name: Blog Post Creation
description: '블로그 게시물 작성 시 필요한 정보를 입력하세요. 괄호 사용은 지양해주세요.'
title: '[Blog] 블로그 제목을 입력하세요.'
labels: ['blog', 'content']
assignees: ['sojuso']

body:
  - type: input
    id: title
    attributes:
      label: '제목'
      description: '블로그 제목을 입력하세요 (필수).'
      placeholder: '블로그 제목을 입력하세요'

  - type: input
    id: tags
    attributes:
      label: '태그'
      description: '쉼표로 구분된 태그 목록을 입력하세요 (예: tech, javascript, openai).'
      placeholder: '예: tech, javascript, openai'

  - type: textarea
    id: summary
    attributes:
      label: '요약'
      description: '이 게시물의 요약을 작성하세요.'

  - type: dropdown
    id: authors
    attributes:
      label: '작성자'
      description: '작성자를 선택하세요.'
      options:
        - kimhyunjoo
        - kimseokju
        - leehanna
        - shinsuyoung
      multiple: true

  - type: dropdown
    id: is_new_post
    attributes:
      label: '신규 생성 여부'
      description: '신규 생성 글인지 확인해주세요.'
      options:
        - 예
        - 아니오
