name: Push to deploy Repo

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sync:
    if: github.repository == 'Team-groupHi/groupHi-blog'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Fork Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "sojuso"
          git config user.email "asdfg7123@gmail.com"

      - name: Add Upstream Remote
        run: |
          git remote add upstream https://github.com/Team-groupHi/groupHi-blog

      - name: Fetch Upstream
        run: |
          git fetch upstream
          git checkout main
          git merge upstream/main

      - name: Push Changes
        run: |
          git push https://sojuso:${{ secrets.ACCESS_TOKEN }}@github.com/sojuso/groupHi-blog.git main
